version: '3' 
services:
  protege-docker-vnc:
    image: openkbs/protege-docker-vnc
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protege-docker-vnc
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    #env_file:
    #  - ./.env
    ports:
      - 5901:5901
      - 6901:5601
    volumes:
      - ./workspace:/home/developer/workspace
      - ./data:/home/developer/data
      -./.Protege:/home/developer/.Protege

